### PR TITLE
App | Fix | Done button from Collections View not changing state afte…

### PR DESCRIPTION
**Pull request by frogman544**
…r Edit

---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### Description
Fix for https://github.com/anyproto/anytype-kotlin/issues/1003

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Mobile & Desktop Screenshots/Recordings

[untitled.webm](https://github.com/anyproto/anytype-kotlin/assets/97510/6cb69dfe-e81f-45cc-9579-26d611b72bc9)

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by frogman544** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by frogman544** [comment]
recheck

**Comment by uburoiubu** [comment]
@frogman544, thanks for contributing. could you attach video with the fix?

**Comment by frogman544** [comment]
@uburoiubu uploaded it to the description, I missed that section the first time :)

**Comment by frogman544** [comment]
@uburoiubu do you think this can be merged or is there anything else I need to do for this PR? Cheers!

**Review by konstantiniiv — APPROVED** [review]

**Review by uburoiubu — APPROVED** [review]

**Comment by fuksman** [comment]
@any contributor @frogman544 code

**Pull request merged**
